name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            Hi @{{ author }},
            We don't address issues here on GitHub, as this is a public mirror! You might want to direct this to https://gitlab.com/wallymer/toffeeOSdocs/-/issues. Thanks!
            
            Your friends,
            toffeeOS Documentation Maintainers
        
          pullRequestOpened: |
            Hi @{{ author }},
            We don't address PRs here on GitHub, as this is a public mirror! You might want to direct this to https://gitlab.com/wallymer/toffeeOSdocs. Thanks!
            
            Your friends,
            toffeeOS Documentation Maintainers
